### ISSUE TITLE
Last release breaks hgetall and hset

### ISSUE THREAD

**Issue by ruanltbg** [redis-store/redis-store#320]
ref: https://github.com/redis-store/redis-store/commit/68e779b9802800edfd3e148bf289c8594ad74865

After upgrading from v1.5 to v1.8 the methods [hset](https://github.com/redis/redis-rb/blob/6b894f85954a82faa1f527d942ead9aade9c1ddc/lib/redis.rb#L2113) and [hgetall](https://github.com/redis/redis-rb/blob/6b894f85954a82faa1f527d942ead9aade9c1ddc/lib/redis.rb#L2282) are modifying the original behaviour. 

Because of the changes on [lib/redis/store/namespace.rb#L70](https://github.com/redis-store/redis-store/blob/68e779b9802800edfd3e148bf289c8594ad74865/lib/redis/store/namespace.rb#L70) The original methods on `redis-rb` are not working anymore as you can check on the log below.

Log for 1.8.0:
```ruby
0> redis = Rails.cache.data
=> #<Redis client v4.1.3 for redis://localhost:6379/0>

0> redis_key = 'mydata:test'
=> "mydata:test"

0> redis.flushall
=> "OK"

0> redis.hgetall(redis_key)
=> {}

0> redis.hset(redis_key, 'mykey1', 'value1')
redis.hset(redis_key, 'mykey2', 'value2')
redis.hset(redis_key, 'mykey3', 'value3')
=> true

# It is supposed to return all my 3 keys
0> redis.hscan_each(redis_key).to_a
=> []

0> redis.hscan(redis_key, 0)
=> ["0", []]

# It was supposed to delete my key and return 1
0> redis.hdel(redis_key, 'mykey1')
=> 0

0> redis.hgetall(redis_key)
=> {"mykey1"=>"value1", "mykey2"=>"value2", "mykey3"=>"value3"}
```

Log for 1.5.0:
```ruby
0> redis = Rails.cache.data
=> #<Redis client v4.1.3 for redis://localhost:6379/0>

0> redis_key = 'mydata:test'
=> "mydata:test"

0> redis.flushall
=> "OK"

0> redis.hgetall(redis_key)
=> {}

0> redis.hset(redis_key, 'mykey1', 'value1')
redis.hset(redis_key, 'mykey2', 'value2')
redis.hset(redis_key, 'mykey3', 'value3')
=> true

0> redis.hscan_each(redis_key).to_a
=> [["mykey1", "value1"], ["mykey2", "value2"], ["mykey3", "value3"]]

0> redis.hscan(redis_key, 0)
=> ["0", [["mykey1", "value1"], ["mykey2", "value2"], ["mykey3", "value3"]]]

0> redis.hdel(redis_key, 'mykey1')
=> 1

0> redis.hgetall(redis_key)
=> {"mykey2"=>"value2", "mykey3"=>"value3"}
```

I can confirm that modifying the [lib/redis/store/namespace.rb](https://github.com/redis-store/redis-store/blob/master/lib/redis/store/namespace.rb) with  this code I can get my things to work:

```ruby
      def hscan(key, cursor, options={})
        namespace(key) { |k| super(k, cursor, options) }
      end

      def hdel(key, *fields)
        namespace(key) { |k| super(k, fields) }
      end

      def hlen(key)
        namespace(key) { |k| super(k) }
      end
```

cc: @angelfan, @tubbo 

PS: There is no description of the latest release neither a Changelog entry.

I will lock the version of this gem until all the methods related to `hset` are overwrite here. 

Please let me know if you need any help or more information.

**Comment by tubbo** [comment]
Thanks @ruanltbg, I used your code in a PR that should fix this issue. :)

**Comment by tubbo** [comment]
this is out as **v1.8.1**

**Comment by flyerlsk** [comment]
@tubbo Hi, I still have issue with two methods, which are broken since 1.5.0: `hkeys` and `hget`.

Similar code to previous example fixes it:
```
      def hget(key, field)
        namespace(key) { |k| super(k, field) }
      end

      def hkeys(key)
        namespace(key) { |k| super(k) }
      end
```

**Comment by tubbo** [comment]
What’s the issue you’re having? Also might be better to make an issue so it’s easier to track.
